### ISSUE TITLE
Clicking on links on the header only works on the link text

### ISSUE THREAD

**Issue by mpressen** [Benefactorum/app#52]
I need to fix 
![image](https://github.com/user-attachments/assets/eaa5eaec-f747-43c6-84b4-3c040215dd66)
the hover effect lets us believe that we don't have to click on the text, but we do :/

It would be much nicer if we can click anywhere in the hover box, that is the expected behaviour imho

**Comment by BigBen-7** [comment]
can i take this??

**Comment by mpressen** [comment]
Hey Bernard ! What a surprise ! Great to have you here ! You're more than welcome to submit a PR ;). 

This project is just starting, code wise. I'm planning to add a devcontainer to help ease contributions. Tell me if you need it asap.

Also don't hesitate to create more issues !

**Comment by BigBen-7** [comment]
sure i'm in.

**Comment by BigBen-7** [comment]
Hey, nothing from you yet
Is it still on?

**Comment by mpressen** [comment]
Hey sorry Bernard, I didn't get  from your answer that you needed a devcontainer to tackle this issue. I'll work on it and ping you when it's ready ;) 
https://github.com/Benefactorum/app/issues/30

**Comment by BigBen-7** [comment]
oh, Apologies for my not-so-clear response. I'll be on standby until you are done with the dev container.

**Comment by mpressen** [comment]
Hey @BigBen-7, dev containers are up :fire: . I added a proper README, it should be easy to onboard now.

**Comment by BigBen-7** [comment]
Thank you, Pressen. First of all, I apologize for my delayed response. I will get to it now. Thank you for assigning this to me.

**Comment by BigBen-7** [comment]
Hey Max, I need some clarity on this project, so I followed the readme and
did all in the read me if you check now you will see I have created my
branch, so I cd in the frontend folder and I didn't see any package.json in
the frontend folder, and npm install throws an error, so I noticed that
ruby on rails is used on this project, I want to know how can I run the
project on my local machine and get to the issue. Also, I have seen some
added issues and I would love to contribute to the success of this recent
one. Thank you.
looking forward to a reply from you soon

**Comment by mpressen** [comment]
Hey @BigBen-7 , do you use vscode ? This should work out-of-the-box.
![image](https://github.com/user-attachments/assets/2169ab49-3071-484e-ad8f-368841ad7783)

FYI This project is using yarn instead of npm. The package.json is a the root of the project. 

PS: `git pull` before trying out again setting up the dev container. 52d72c1619fbcf536307fac4d2a9718e427a74d3 might avoid you a bug.

**Comment by BigBen-7** [comment]
Hey max, it's me again, I have done all necessary installations but I can't get the server to start running, I also installed rails but still I can't get the server to run with the bin/dev command, it keeps saying no 'bin' is not recognized as an internal or external command, operable program or batch file.

so my question How do I run the server?

**Comment by mpressen** [comment]
Hey Bernard, you don't need to install Ruby, Rails, npm packages, whatsoever. 
It's already done automatically when you launch the dev container.

I tried this setup on 2 other computers, it worked out-of-the-box (as long as you have docker installed).

As far as a guess can help, when you run bin/dev, you're probably not in the dev container (you can run `pwd` to check if you're inside the container or still in your file system).
  
What distrib are you using, which code editor, which docker version ? 
Can you provide me with screenshots, errors messages ?

**Comment by BigBen-7** [comment]
- Visual Studio Code 
- Docker version 27.3.1, build ce12230

When i run bin/dev
![image](https://github.com/user-attachments/assets/38d787fe-820f-48c6-aa33-fa901940788a)

**Comment by mpressen** [comment]
Ok Bernard, looks like you didn't exactly follow the guidelines :p. I'll update it to make it more straightforward for newcomers to dev containers.

1. Don't `cd bin` but stay at the root of the repo.
2. You need to run `bin/dev` inside the dev container.

--> When you are in your benefactorum repo, just open your VsCode editor. It should pop a 'install Dev Container extension' and then another popup 'Reopen in container'. From the vs code integrated terminal, run `pwd` to confirm that you are indeed inside the dev container, and then run `bin/dev` . 'http://localhost:3000' should be live.

Hopefully this time you're gonna make this work.

[EDIT] cca9278a3d183bc7a29c308a89fa5ee6d9293036

**Comment by BigBen-7** [comment]
i got it all  right now, and this  is what I got;
![{3491BD79-A501-455A-A373-981B527CB4C8}](https://github.com/user-attachments/assets/cf32de85-b669-4a27-a365-1254043eb31d)

**Comment by mpressen** [comment]
Great progress !

Your problem looks related to your own setup now.
`\r` makes me think you're running on windows, and `\r` is not compatible with containers as they're UNIX based.

Are you using WSL ? If not I strongly advice you to, you're DX will be enhanced.

You're on your own to debug that, but I prompted chatGPT for you to give you a starting point :
https://chatgpt.com/share/6752eac1-b16c-8005-953e-7d2c8c7bcaa7
and :
```ruby
# If you're seeing issues with `\r`, it likely means files were saved with Windows-style line endings. 
# You can use the following command to convert line endings to Unix-style:

find . -type f -exec dos2unix {} \;

# If you don't have dos2unix installed, you can use sed as an alternative:

find . -type f -exec sed -i 's/\r$//' {} \;

# Make sure your Git is also configured to prevent this issue in the future:
git config --global core.autocrlf input

# If you're running on WSL and still encounter issues, verify that WSL is handling file systems correctly:
wsl --set-default-version 2

```

**Comment by mpressen** [comment]
34d688564d1908302f9510eb66bd4136eb4461ff
