### ISSUE TITLE
Refactor usage of sessionStorage for Sign Up

### ISSUE THREAD

**Issue by mpressen** [Benefactorum/app#75]
it might be possible to use https://inertia-rails.dev/guide/remembering-state instead.

I feel this code is a smell
![image](https://github.com/user-attachments/assets/7d56693b-0d30-4c30-a6f6-b8f2823d4f28)

**Comment by rickystar04** [comment]
Why not use cookies?

**Comment by mpressen** [comment]
Hey ricky, thanks for passing by. Cookies are for a different use case in my opinion. I use them for session id to keep users connected. I don't want to use them for ephemeral client side state.
Here, using Inertia internals is probably the best replacement. I tried it and couldn't manage to make it work on the first go. I opened this issue to give it another try. It's also a learning opportunity to me.

**Comment by mpressen** [comment]
After more investigation, I managed to make remembering state work, but its behaviour is actually not what I expected. Using sessionStorage is fine
